services:
  #Reverse proxy is only for local testing!
  proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8090:80"
    networks:
     - app_network
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    depends_on:
      - idp_keycloak
      - platform-frontend
      - tic-tac-toe-frontend
      - go-frontend
      - platform-backend
      - tic-tac-toe-backend
      - go-backend

  tic-tac-toe-frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team14/games/tic-tac-toe/tic-tac-toe-frontend
    container_name: tic-tac-toe-frontend
    networks:
     - app_network
    environment:
      VITE_KC_URL: http://localhost:8090/auth
      VITE_KC_REALM: FourteenGames
      VITE_KC_CLIENT_ID: TTT-frontend
    ports:
      - "8091:80"

  go-frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team14/games/go/go-frontend
    container_name: go-frontend
    networks:
      - app_network
    environment:
      VITE_BASENAME: /gamehosts/go
      VITE_KC_URL: http://localhost:8090/auth
      VITE_KC_REALM: FourteenGames
      VITE_KC_CLIENT_ID: go-frontend
    ports:
      - "8092:80"

  tic-tac-toe-backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team14/games/tic-tac-toe/tic-tac-toe-backend
    container_name: tic-tac-toe-backend
    expose:
      - "8081"
    networks:
     - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://platform-db:5432/postgres?currentSchema=tictactoe  
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: false
      SPRING_SQL_INIT_MODE: always
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:8090/auth/realms/FourteenGames
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://idp_keycloak:8080/auth/realms/FourteenGames/protocol/openid-connect/certs
      CORS_ALLOWED-ORIGINS: "http://localhost:8090"
    depends_on:
      - platform-db
      - idp_keycloak

  go-backend:
    image: go-backend
    container_name: go-backend
    expose:
      - "8082"
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://platform-db:5432/postgres?currentSchema=go
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: false
      SPRING_SQL_INIT_MODE: always
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:8090/auth/realms/FourteenGames
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://idp_keycloak:8080/auth/realms/FourteenGames/protocol/openid-connect/certs
      CORS_ALLOWED-ORIGINS: "http://localhost:8090"
      SPRING_RABBITMQ_ADDRESSES: "mq_rabbitmq:5672"
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      SPRING_RABBITMQ_FOURTEENGAMES_INTERNAL-GAME-URL: http://proxy/gamehosts/go/
      SPRING_RABBITMQ_FOURTEENGAMES_EXTERNAL-GAME-URL: http://localhost:8090/gamehosts/go/
    depends_on:
      platform-db:
        condition: service_started
      idp_keycloak:
        condition: service_started
      mq_rabbitmq:
        condition: service_healthy

  platform-frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team14/platform/platform-frontend
    container_name: platform-frontend
    networks:
     - app_network
    environment:
      VITE_KC_URL: http://localhost:8090/auth
      VITE_KC_REALM: FourteenGames
      VITE_KC_CLIENT_ID: platform-frontend
    expose:
      - "80"

  platform-backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team14/platform/platform-backend
    container_name: platform-backend-image
    expose:
      - "8080"
    networks:
     - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://platform-db:5432/postgres?currentSchema=platform  
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: false
      SPRING_SQL_INIT_MODE: always
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:8090/auth/realms/FourteenGames
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://idp_keycloak:8080/auth/realms/FourteenGames/protocol/openid-connect/certs
      CORS_ALLOWED-ORIGINS: "http://localhost:8090"
      SPRING_RABBITMQ_ADDRESSES: mq_rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
    depends_on:
      platform-db:
        condition: service_started
      idp_keycloak:
        condition: service_started
      mq_rabbitmq:
        condition: service_healthy


  platform-db:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      PGDATA: postgresql_pgdata
    ports:
      - '5443:5432'
    networks:
     - app_network
    volumes:
      - postgresql_data:/var/lib/postgresql
      - ./init-scripts/sql:/docker-entrypoint-initdb.d/

  idp_mysql:
    image: mysql:9.0.1
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'keycloak'
      MYSQL_PASSWORD: 'password'
    expose:
      - '3306'
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  idp_keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: idp_keycloak
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_DB: 'mysql'
      KC_DB_URL_HOST: 'idp_mysql'
      KC_DB_URL_DATABASE: 'keycloak'
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'password'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_HOSTNAME: 'http://localhost:8090/auth'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_RELATIVE_PATH: '/auth'
    command: start --import-realm
    ports:
      - "8080:8080"
    depends_on:
      idp_mysql:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      # make sure to delete any 'authorizationSettings' from realm-export.json
      - ./keycloak/import/realm-export.json:/opt/keycloak/data/import/FourteenGames-realm.json

  mq_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: mq_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #MGMT
    networks:
      - app_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:
  rabbitmq_data:
  rabbitmq_log:
  postgresql_data:
  postgresql_pgdata:

networks:
  app_network:

# Reverse proxy only required for running dockerized locally.
configs:
  nginx-config:
    content: |
      events {}

      http {
        server {
          listen 80;
      
          location /auth/ {
            proxy_pass http://idp_keycloak:8080;
      
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }

          location /gamehosts/tic-tac-toe/ {
            proxy_pass http://tic-tac-toe-frontend/;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }
      
          location /gamehosts/go/ {
            proxy_pass http://go-frontend/;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }
      
          # API's
          location /api/ {
            proxy_pass http://platform-backend:8080/api/;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }

          location /tic-tac-toe/api/ {
            proxy_pass http://tic-tac-toe-backend:8081/tic-tac-toe/api/;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }

          location /go/api/ {
            proxy_pass http://go-backend:8082/go/api/;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }

          # MAIN FRONTEND
          location / {
            proxy_pass http://platform-frontend:80;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
          }

        }
      }